// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package launcher

import (
	"github.com/leiqD/go-socket5/infra"
)

// Injectors from wire.go:

func InitializeConfig(cfgPath string) *infra.Configs {
	viper := infra.NewViper(cfgPath)
	configs := infra.NewConfig(viper)
	return configs
}
